# -*- coding: utf-8 -*-
{
    "name": "POS Extended",
    "version": "15.0.0.0.1",
    "category": "Point of Sale",
    'summary': '',
    "description": """""",
    "author": "Walnut Software Solutions",
    "website": "www.walnutit.com",
    "depends": ['pos_hr', 'product_extended', 'product_brand', 'pos_discount'],
    "data": [
        'security/pos_security.xml',
        'security/ir.model.access.csv',
        'views/menu.xml',
        'views/pos_return_reason_view.xml',
        'views/pos_config_view.xml',
        'views/res_users_view.xml',
        'views/pos_payment_method_view.xml',
        'views/pos_payment_view.xml',
        'views/pos_order_view.xml',
        'views/pos_order_report_view.xml',
    ],
    'qweb': [
    ],
    'assets': {
        'point_of_sale.assets': [
            'pos_extended/static/lib/JsBarcode.all.min.js',
            'pos_extended/static/src/css/pos.css',
            'pos_extended/static/src/js/db.js',
            'pos_extended/static/src/js/models.js',
            'pos_extended/static/src/js/ChromeWidgets/CashierName.js',
            'pos_extended/static/src/js/ChromeWidgets/OrderModeButton.js',
            'pos_extended/static/src/js/Popups/SelectionPopup.js',
            'pos_extended/static/src/js/Popups/ProductInfoPopup.js',
            'pos_extended/static/src/js/Popups/PaymentNotePopup.js',
            'pos_extended/static/src/js/Popups/UpdatePaymentPopup.js',
            'pos_extended/static/src/js/Popups/CashMovePopup.js',
            'pos_extended/static/src/js/Popups/DiscountPopup.js',
            'pos_extended/static/src/js/Popups/ClosePosPopup.js',
            'pos_extended/static/src/js/Screens/SetReturnReasonButton.js',
            'pos_extended/static/src/js/Screens/ProductScreen/ProductQuantityCounter.js',
            'pos_extended/static/src/js/Screens/ProductScreen/ControlButtonsInherit.js',
            'pos_extended/static/src/js/Screens/ProductScreen/ActionpadWidget.js',
            'pos_extended/static/src/js/Screens/ProductScreen/NumpadWidget.js',
            'pos_extended/static/src/js/Screens/ProductScreen/Orderline.js',
            'pos_extended/static/src/js/Screens/ProductScreen/ProductScreen.js',
            'pos_extended/static/src/js/Screens/ReceiptScreen/OrderReceipt.js',
            'pos_extended/static/src/js/Screens/TicketScreen/TicketScreen.js',
            'pos_extended/static/src/js/Screens/PaymentScreen/PaymentScreenStatus.js',
            'pos_extended/static/src/js/Screens/PaymentScreen/PaymentScreen.js',
            'pos_extended/static/src/js/Chrome.js',
        ],
        'web.assets_qweb': [
            'pos_extended/static/src/xml/**/*',
        ],
    },
    "auto_install": False,
    "installable": True,
    'license': 'OPL-1'
}
